#this line is only because we won't install libs on the AWS
.libPaths("/data/R-lib")
# For more information see: http://www.bioconductor.org/help/workflows/rnaseqGene/
library("tidyverse")
library("DESeq2")
#set working dir

workdir <- '/scratch/Users/username/day7/'
dir.create(workdir, showWarnings = FALSE)
setwd(workdir)
getwd()
outdir <- paste(workdir, 'deseqresults', '/', sep='') ##naming our outdir
dir.create(outdir, showWarnings = FALSE) ###creating the directory

#### LOAD IN DATA (CHOOSE ONE) ###########################
### featureCounts: read in count data, define counts, and define group
counts <- read.csv("/scratch/Shares/public/sread2021/cookingShow/day6_7/inf_featureCounts_gene_rnaseq.txt", row.names=1, sep="\t")
head(counts) #your rowname should be the gene ids. Your colnames should match some column of your metadata table (in this case filetable)
filetable <- read.csv("/scratch/Shares/public/sread2021/cookingShow/day6_7/bam_table.csv", row.names=1)
head(counts)
filetable$ifn_treat <- factor(filetable$ifn_treat)

#Your metatdata columns and your counts rows must be in the same order!!!!!!
counts <- counts %>% select(as.vector(filetable$sampID))

# Generate DESeqDataSet from count matrix generated by featureCounts
ddsMat <- DESeqDataSetFromMatrix(countData = counts, colData = filetable, design=~ifn_treat)
dds <- ddsMat

### Filter out all rows with total count less than or equal to 1
nrow(dds)
dds <- dds[ rowSums(counts(dds)) > 1, ]
nrow(dds)

### Run DESeq on the DESeqDataSet object
DEdds <- DESeq(dds)

### output the results for a specified alpha value
alpha_val <- 0.05
comparison <- c("ifn_treat", "ifn", "ctrl")
res_ifn <- results(DEdds, alpha = alpha_val, contrast = comparison)

res_shrink_ifn <- lfcShrink(DEdds, contrast = comparison, res = res_ifn)

### MA plot
name <- "MA_ifn_vs_ctrl_DEA"
limits <- c(-10, 10)
pdf(paste0(outdir, name, ".pdf"))
maplot <- plotMA(res_shrink_ifn, main="IFN treatment", alpha=alpha_val, ylim=limits)
dev.off()


### Take subset of results that are significant
res_shrink_Sig <- subset(res_shrink_ifn, padj < alpha_val)

write.csv(res_shrink_Sig, file = paste0(outdir,"my_results.csv"))

